title: Osayande David
logo: OIP.webp
description: Data-driven professional with over 2 years of experience in analytics and business intelligence, 
skilled at transforming complex datasets into actionable insights that drive strategic decisions. 
Adept at data cleaning, visualization, and statistical analysis, with proven expertise in identifying 
trends and developing predictive models to optimize business outcomes.
Proficient in SQL, Power BI, and Excel, with a strong command of data manipulation, reporting automation, 
and dashboard development. Known for exceptional attention to detail, problem-solving abilities, 
and clear communication of analytical findings to technical and non-technical audiences. 
Passionate about leveraging data to improve performance, uncover opportunities, and support organizational growth.  
#show_downloads: true
#google_analytics: 
theme: jekyll-theme-minimal
