title: Osayande David
logo: OIP.webp
description: | A collection of data analytics and business intelligence projects showcasing my expertise in Power BI, SQL, and Excel. 
Each project demonstrates my ability to clean, model, and visualize data to uncover insights, track KPIs, and support data-driven decision-making. 
From interactive dashboards to predictive analysis, this portfolio highlights how I transform complex datasets into clear, actionable business insights.  

#show_downloads: true
#google_analytics: 
theme: jekyll-theme-minimal
